<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <NoWarn>SYSLIB0014;CA1416</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../src/Nucleo/**/*.cs" />
  </ItemGroup>
</Project>
